name: "Publish to NPM"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - id: check
        uses: EndBug/version-check@v3
        with:
          file-url: https://unpkg.com/theme-change@latest/package.json
          static-checking: localIsNew
      - run: bun install
      - name: mkdir
        run: mkdir -p dist
      - name: build
        run: bun build.mjs
      - name: publish
        run: bun publish
        if: steps.check.outputs.changed == 'true'
        env:
          NPM_CONFIG_TOKEN: ${{secrets.NPM_TOKEN}}
